### PR TITLE
Add jsxNotEquals, jsxIncludes, and jsxNotIncludes

### PR DESCRIPTION
**Pull request by joerter**
Hi, thanks for creating this add on to tape! I had the need for jsxIncludes in my projects, so I added that along with the other methods from expect-jsx. Let me know what you think!

### CODE REVIEW

**Comment by atabel** [comment]
Good idea, but I think each extension should be in an independent npm module. Then for simplicity we can create a tape-jsx-extensions module which include all. This way, if some user only need one extension, he doesn't have to install all, and if you need all you can install the tape-jsx-extensions module
What do you think?

**Comment by joerter** [comment]
I agree, that makes a lot of sense to let users decide exactly which extensions they want.

**Comment by atabel** [comment]
I have created the `tape-jsx-extensions` module: https://github.com/atabel/tape-jsx-extensions
Currently it only has the jsxEquals assertion. If you want you can publish your assertions as independent packages and add a pull request to the `tape-jsx-extensions` repo to include them

**Comment by joerter** [comment]
Cool, I'll get on that!

**Pull request closed without merging**
